version: '3.8'

services:
  flaskapp:
    image: flaskapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql-service
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: test
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1

volumes:
  mysql-data:
